import * as THREE from 'three';

export const mats = {
  grass: new THREE.MeshStandardMaterial({ color: 0x2a5e2a, roughness: 0.97 }),
  grassDeep: new THREE.MeshStandardMaterial({ color: 0x1a4720, roughness: 0.98 }),
  path: new THREE.MeshStandardMaterial({ color: 0x6e5a38, roughness: 0.92 }),
  dirt: new THREE.MeshStandardMaterial({ color: 0x4a3820, roughness: 0.96 }),
  trunk: new THREE.MeshStandardMaterial({ color: 0x3e2818, roughness: 0.88 }),
  trunkMossy: new THREE.MeshStandardMaterial({ color: 0x354828, roughness: 0.9 }),
  leaves: new THREE.MeshStandardMaterial({
    color: 0x1c6e2a,
    roughness: 0.78,
    flatShading: true,
  }),
  leavesDark: new THREE.MeshStandardMaterial({
    color: 0x0f4018,
    roughness: 0.82,
    flatShading: true,
  }),
  leavesBright: new THREE.MeshStandardMaterial({
    color: 0x3a8a38,
    roughness: 0.75,
    flatShading: true,
  }),
  bush: new THREE.MeshStandardMaterial({ color: 0x246e2c, roughness: 0.88, flatShading: true }),
  fern: new THREE.MeshStandardMaterial({
    color: 0x2d7a40,
    roughness: 0.7,
    side: THREE.DoubleSide,
  }),
  stone: new THREE.MeshStandardMaterial({
    color: 0x7e786c,
    roughness: 0.82,
    metalness: 0.04,
  }),
  stoneDark: new THREE.MeshStandardMaterial({
    color: 0x4a4640,
    roughness: 0.88,
    metalness: 0.05,
  }),
  stoneAccent: new THREE.MeshStandardMaterial({
    color: 0xa09068,
    roughness: 0.72,
    metalness: 0.08,
  }),
  stoneWeathered: new THREE.MeshStandardMaterial({
    color: 0x6a6558,
    roughness: 0.9,
    metalness: 0.03,
  }),
  moss: new THREE.MeshStandardMaterial({
    color: 0x3a6a38,
    roughness: 0.95,
    emissive: 0x0a1a08,
    emissiveIntensity: 0.08,
  }),
  vine: new THREE.MeshStandardMaterial({ color: 0x1e5028, roughness: 0.85 }),
  gold: new THREE.MeshStandardMaterial({
    color: 0xffd700,
    metalness: 0.92,
    roughness: 0.22,
    emissive: 0x664400,
    emissiveIntensity: 0.4,
  }),
  torchMetal: new THREE.MeshStandardMaterial({ color: 0x444444, metalness: 0.7, roughness: 0.4 }),
  flame: new THREE.MeshStandardMaterial({
    color: 0xff8800,
    emissive: 0xff6600,
    emissiveIntensity: 1.4,
    transparent: true,
    opacity: 0.92,
  }),
  water: new THREE.MeshStandardMaterial({
    color: 0x2a6080,
    transparent: true,
    opacity: 0.7,
    roughness: 0.2,
    metalness: 0.3,
  }),
  spike: new THREE.MeshStandardMaterial({
    color: 0x8a8880,
    metalness: 0.55,
    roughness: 0.3,
    emissive: 0x221100,
    emissiveIntensity: 0.15,
  }),
  plate: new THREE.MeshStandardMaterial({ color: 0x6a6050, roughness: 0.65, metalness: 0.1 }),
  plateDanger: new THREE.MeshStandardMaterial({
    color: 0x8a5040,
    emissive: 0x441808,
    emissiveIntensity: 0.35,
    roughness: 0.55,
  }),
  plateActive: new THREE.MeshStandardMaterial({
    color: 0xcc4433,
    emissive: 0xaa2200,
    emissiveIntensity: 0.75,
    roughness: 0.45,
  }),
  plateSafe: new THREE.MeshStandardMaterial({
    color: 0x4a7a50,
    emissive: 0x1a3a20,
    emissiveIntensity: 0.4,
    roughness: 0.5,
  }),
  plateNext: new THREE.MeshStandardMaterial({
    color: 0xd4a030,
    emissive: 0x886010,
    emissiveIntensity: 0.65,
    roughness: 0.45,
  }),
  dart: new THREE.MeshStandardMaterial({ color: 0x2a1a10, roughness: 0.55, metalness: 0.2 }),
  beam: new THREE.MeshStandardMaterial({
    color: 0xffcc44,
    emissive: 0xffaa22,
    emissiveIntensity: 2.0,
    transparent: true,
    opacity: 0.62,
    depthWrite: false,
  }),
  dangerRing: new THREE.MeshStandardMaterial({
    color: 0xff4422,
    emissive: 0xff2200,
    emissiveIntensity: 0.8,
    transparent: true,
    opacity: 0.45,
    side: THREE.DoubleSide,
    depthWrite: false,
  }),
  jaguarBody: new THREE.MeshStandardMaterial({ color: 0xc48a2a, roughness: 0.68 }),
  jaguarSpot: new THREE.MeshStandardMaterial({ color: 0x1a1208, roughness: 0.8 }),
  jaguarBelly: new THREE.MeshStandardMaterial({ color: 0xe8d0a0, roughness: 0.75 }),
  jaguarEye: new THREE.MeshStandardMaterial({
    color: 0xffee44,
    emissive: 0xffcc00,
    emissiveIntensity: 0.3,
  }),
  jaguarEyeAlert: new THREE.MeshStandardMaterial({
    color: 0xffaa22,
    emissive: 0xff8800,
    emissiveIntensity: 1.2,
  }),
  jaguarEyeChase: new THREE.MeshStandardMaterial({
    color: 0xff4422,
    emissive: 0xff1100,
    emissiveIntensity: 1.6,
  }),
  playerBody: new THREE.MeshStandardMaterial({ color: 0x3a6a9a, roughness: 0.7 }),
  playerSkin: new THREE.MeshStandardMaterial({ color: 0xd4a574, roughness: 0.7 }),
  playerHat: new THREE.MeshStandardMaterial({ color: 0x8b6914, roughness: 0.8 }),
};
