import * as THREE from 'three';

export const mats = {
  grass: new THREE.MeshStandardMaterial({ color: 0x2d6b2d, roughness: 0.95 }),
  path: new THREE.MeshStandardMaterial({ color: 0x6b5a3a, roughness: 0.9 }),
  dirt: new THREE.MeshStandardMaterial({ color: 0x4a3a22, roughness: 0.95 }),
  trunk: new THREE.MeshStandardMaterial({ color: 0x4a3020, roughness: 0.85 }),
  leaves: new THREE.MeshStandardMaterial({ color: 0x1e6b28, roughness: 0.8 }),
  leavesDark: new THREE.MeshStandardMaterial({ color: 0x14501c, roughness: 0.85 }),
  bush: new THREE.MeshStandardMaterial({ color: 0x287a30, roughness: 0.9 }),
  stone: new THREE.MeshStandardMaterial({ color: 0x8a8478, roughness: 0.75, metalness: 0.05 }),
  stoneDark: new THREE.MeshStandardMaterial({ color: 0x5a564c, roughness: 0.8 }),
  stoneAccent: new THREE.MeshStandardMaterial({ color: 0xa89870, roughness: 0.7 }),
  moss: new THREE.MeshStandardMaterial({ color: 0x3a6a38, roughness: 0.9 }),
  gold: new THREE.MeshStandardMaterial({
    color: 0xffd700,
    metalness: 0.9,
    roughness: 0.25,
    emissive: 0x664400,
    emissiveIntensity: 0.35,
  }),
  torchMetal: new THREE.MeshStandardMaterial({ color: 0x444444, metalness: 0.7, roughness: 0.4 }),
  flame: new THREE.MeshStandardMaterial({
    color: 0xff8800,
    emissive: 0xff6600,
    emissiveIntensity: 1.2,
    transparent: true,
    opacity: 0.9,
  }),
  water: new THREE.MeshStandardMaterial({
    color: 0x2a6080,
    transparent: true,
    opacity: 0.7,
    roughness: 0.2,
    metalness: 0.3,
  }),
  spike: new THREE.MeshStandardMaterial({ color: 0x666660, metalness: 0.5, roughness: 0.35 }),
  plate: new THREE.MeshStandardMaterial({ color: 0x7a7060, roughness: 0.6 }),
  plateActive: new THREE.MeshStandardMaterial({
    color: 0xaa4444,
    emissive: 0x441111,
    emissiveIntensity: 0.5,
    roughness: 0.5,
  }),
  dart: new THREE.MeshStandardMaterial({ color: 0x3a2a1a, roughness: 0.6 }),
  beam: new THREE.MeshStandardMaterial({
    color: 0xffcc44,
    emissive: 0xffaa22,
    emissiveIntensity: 1.5,
    transparent: true,
    opacity: 0.55,
  }),
  jaguarBody: new THREE.MeshStandardMaterial({ color: 0xc48a2a, roughness: 0.7 }),
  jaguarSpot: new THREE.MeshStandardMaterial({ color: 0x1a1208, roughness: 0.8 }),
  jaguarBelly: new THREE.MeshStandardMaterial({ color: 0xe8d0a0, roughness: 0.75 }),
  playerBody: new THREE.MeshStandardMaterial({ color: 0x3a6a9a, roughness: 0.7 }),
  playerSkin: new THREE.MeshStandardMaterial({ color: 0xd4a574, roughness: 0.7 }),
  playerHat: new THREE.MeshStandardMaterial({ color: 0x8b6914, roughness: 0.8 }),
};
